# Generated by Django 2.2.1 on 2019-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=512)),
                ('sex', models.IntegerField(max_length=1)),
                ('age', models.IntegerField(max_length=3)),
                ('vote_count', models.IntegerField(max_length=7)),
            ],
        ),
    ]
